/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles = ["h1[_ngcontent-%COMP%] {\r\n    color: green;\r\n}"];
export { styles as styles };
